{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: taweret-metrics-service
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "2112"
    prometheus.io/scrape: "true"
  labels:
    {{- include "taweret.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "taweret.selectorLabels" . | nindent 4 }}
  ports:
  - name: taweret-metrics-service-port
    protocol: TCP
    port: 2112
    targetPort: metrics
{{- end }}
