{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "taweret.serviceAccountName" . }}
  labels:
    {{- include "taweret.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.serviceAccount.createRBAC -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "taweret.serviceAccountName" . }}-role
rules:
    - apiGroups: ['cr.kanister.io']
      resources: ['actionsets']
      verbs: ['create', 'delete', 'get', 'list', 'watch']
    - apiGroups: ['cr.kanister.io']
      resources: ['blueprints', 'profiles']
      verbs: ['get']
    - apiGroups: ['apps']
      resources: ['statefulsets']
      verbs: ['get']
    - apiGroups: ['']
      resources: ['namespaces']
      verbs: ['get']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "taweret.serviceAccountName" . }}-rolebinding
subjects:
    - kind: ServiceAccount
      name: {{ include "taweret.serviceAccountName" . }}
roleRef:
    kind: Role
    name: {{ include "taweret.serviceAccountName" . }}-role
    apiGroup: rbac.authorization.k8s.io
{{- end }}
