name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{ steps.run-goreleaser.outputs.metadata }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Fetch all tags
        run: git fetch --force --tags
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      -
        id: run-goreleaser
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TAWERET_GITHUB_SECRET }}

  docker:
    runs-on: ubuntu-latest
    needs: [goreleaser]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RENKU_DOCKER_USERNAME }}
          password: ${{ secrets.RENKU_DOCKER_PASSWORD }}
      -
        name: get version tag from goreleaser metadata output
        run: echo "TAG_VERSION=$(echo $json_var | jq '.tag' | tr -d '\"v')" >> $GITHUB_ENV
        env: 
          json_var: ${{ needs.goreleaser.outputs.metadata }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 'renku/taweret:${{ env.TAG_VERSION }}'
